import "@/app/globals.css";

import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { NextIntlClientProvider, useMessages } from "next-intl";

// import { getTranslations } from "next-intl/server";
// import { z } from "zod";
import { Layout } from "@/components/Layout";
const notoSansJp = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();
  // const t = await getTranslations();

  // const customErrorMap: z.ZodErrorMap = (issue, ctx) => {
  //   if (issue.code === z.ZodIssueCode.invalid_type) {
  //     if (issue.expected === "number") {
  //       return { message: "hello" };
  //     }
  //   }

  //   return { message: ctx.defaultError };
  // };

  // z.setErrorMap(customErrorMap);

  return (
    <html lang={params.locale}>
      <body className={notoSansJp.className}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <Layout>{children}</Layout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
