import "@/app/globals.css";

import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";

import { Layout } from "@/components/Layout";

const notoSansJp = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={params.locale}>
      <body className={notoSansJp.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
